name: flutter_webrtc_fixed_v0_12_0_example
description: Demonstrates how to use the flutter_webrtc_fixed_v0_12_0 plugin.
version: 0.1.0
publish_to: "none" # Remove this line if you wish to publish this package

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_webrtc_fixed_v0_12_0:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
