name: flutter_webrtc_fixed_v0.12.0
description: Flutter WebRTC plugin for iOS/Android/Destkop/Web, based on GoogleWebRTC. Fixed version with improvements and bug fixes.
version: 0.12.0
homepage: https://github.com/boughdiri-dorsaf/flutter_webrtc_fixed_v0.12.0
environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=1.22.0"

dependencies:
  collection: ^1.17.0
  dart_webrtc: ^1.4.9
  flutter:
    sdk: flutter
  path_provider: ^2.0.2
  web: ^1.0.0
  webrtc_interface: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  lints: ^4.0.0
  pedantic: ^1.11.1
  test: any

flutter:
  plugin:
    platforms:
      android:
        package: com.cloudwebrtc.webrtc
        pluginClass: FlutterWebRTCPlugin
      ios:
        pluginClass: FlutterWebRTCPlugin
      macos:
        pluginClass: FlutterWebRTCPlugin
      windows:
        pluginClass: FlutterWebRTCPlugin
      linux:
        pluginClass: FlutterWebRTCPlugin
      elinux:
        pluginClass: FlutterWebRTCPlugin
